locale: "en-US"
title: "Garvit Goyal"
title_separator: "-"
name: &name "Garvit Goyal"
description: &description "Machine learning researcher working on reliable ML, AutoML, and representation learning."
url: "https://garvit-goyal.github.io"
baseurl: ""
repository: "garvit-goyal/garvit-goyal.github.io"
remote_theme: "academicpages/academicpages.github.io@master"
og_image: "/images/profile.jpg"

author:
  avatar: "profile.jpg"
  name: "Garvit Goyal"
  pronouns:
  bio: "Machine Learning Researcher"
  location: "New Delhi, India"
  employer:
  uri:
  email: "garvitgoyal98@gmail.com"
  cv: "/files/Garvit_Goyal_CV.pdf"
  arxiv:
  googlescholar:
  orcid:
  semantic:
  openreview:
  researchgate:
  github: "garvit-goyal"
  linkedin: "garvit25"
  twitter:
  bluesky:

breadcrumbs: false
future: true
read_more: "disabled"
talkmap_link: false
comments:
  provider:
atom_feed:
  hide: true

analytics:
  provider: false
  google:
    tracking_id: "G-8EX5F1SVZH"

include:
  - _pages
  - files

exclude:
  - README.md
  - NOTICE
  - Gemfile
  - vendor
  - node_modules

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Asia/Kolkata

plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

whitelist:
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

compress_html:
  clippings: all
  ignore:
    envs: development
